server:
  port: 8088
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: always

internal:
  api:
    shopping-service:
      url: http://web-shopping-service:8087/shopping/cart

spring:
  data:
    mongodb:
      host: web-mongodb
      port: 27017
      database: order
      username: order-service
      password: Password123!

logging:
  level:
    root: INFO
    com.example.weborderservice: DEBUG